# Generated by Django 2.2.6 on 2019-10-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191015_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('publish', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='waijian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.publisher'),
            preserve_default=False,
        ),
    ]
